apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx-pod
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx-pod
    spec:
      containers:
      - name: nginx
        image: nginx:1.21.1-alpine
        ports:
          - containerPort: 80
        volumeMounts:
        - name: conf
          mountPath: /nginx/nginx.conf
        - name: pass
          mountPath: /nginx/nginx.pass
      volumes:
        - name: conf
          configMap:
            name: nginx-config
        - name: pass
          secret:
            secretName: nginx-pass
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-node-port
spec:
  selector:
    app: nginx-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-balance
spec:
  selector:
    app: nginx-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: web-nginx
  namespace: default
spec:
  selector:
    app: nginx-pod
  externalName: sf-nginx
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  type: ExternalName
